server:
  port: 8081
  servlet:
    context-path: /
spring:
  rabbitmq:
    max-retries: ${MAX_RETRIES:3}
    listener:
      simple:
        default-requeue-rejected: false
  mail:
    host: ${SMTP_HOST:mail.intexsoft.by}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:pavel.lotashinski@intexsoft.by}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
telegram:
  token: ${TOKEN:2025620834:AAEKFyfG86egIuBODQwermnNnJHV0JpA2wA}
  name: ${BOT_NAME:Java-Topics}
