version: "3"

services:
  db-java-topics:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pavel
      POSTGRES_USER: pavel
      POSTGRES_DB: topics
  rabbitmq-java-topics:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"