server:
  port: 8080
  servlet:
    context-path: /
spring:
  liquibase:
    change-log: classpath:changelog.xml
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        ddl-auto: none
        current_session_context_class: thread
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
      ${DATABASE_URL:jdbc:postgresql://localhost:5432/topics}
    username: ${DATABASE_USERNAME:pavel}
    password: ${DATABASE_PASSWORD:pavel}
path:
  data:
    json:
      ${PATH_TO_JSON:/home/INTEXSOFT/pavel.lotashinski/work/java-topics/}
profile:
  DB
